CC = gcc
PROGNAME = bplus
SRCS =  main.c insert.c mknode.c member.c delete.c
OBJS =  main.o insert.o mknode.o member.o delete.o
CFLAGS = -g
CLIBS =

all: $(PROGNAME)

$(PROGNAME): $(OBJS) 
	$(CC) $(CFLAGS) -o $(PROGNAME) $(OBJS) $(CLIBS)

clean:
	rm -f core *.o

### Dependencies








# DO NOT DELETE



